name       : global
version    : 6.5.7
release    : 1
source     :
    - https://ftp.gnu.org/pub/gnu/global/global-6.5.7.tar.gz : d9c08fa524f9499b54241cb2d72f8a7df01453b6d5e012a63784ded08e3acd32
license    : GPL-3.0
component  : programming.tools
summary    : GNU GLOBAL is a source code tagging system that works the same way across diverse environments
description: |
    GNU GLOBAL is a source code tagging system that works the same way across diverse environments, such as Emacs editor, Vi editor, Less viewer, Bash shell, various web browsers, etc.
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 0644 $pkgfiles/gtags.tmpfiles $installdir/%libdir%/tmpfiles.d/gtags.conf
