name       : global
version    : 6.6.3
release    : 4
source     :
    - https://mirrors.rit.edu/gnu/global/global-6.6.3.tar.gz : cbee98ef6c1b064bc5b062d14a6d94dca67289e8374860817057db7688bc651c
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GNU GLOBAL is a source code tagging system that works the same way across diverse environments
description: |
    GNU GLOBAL is a source code tagging system that works the same way across diverse environments, such as Emacs editor, Vi editor, Less viewer, Bash shell, various web browsers, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 0644 $pkgfiles/gtags.tmpfiles $installdir/%libdir%/tmpfiles.d/gtags.conf
