name       : global
version    : 6.6.1
release    : 3
source     :
    - https://ftp.gnu.org/pub/gnu/global/global-6.6.1.tar.gz : 943dc440382d82454786bfd92b86946961cb2196039eceffd7eb551ac83759e4
license    : GPL-3.0
component  : programming.tools
summary    : GNU GLOBAL is a source code tagging system that works the same way across diverse environments
description: |
    GNU GLOBAL is a source code tagging system that works the same way across diverse environments, such as Emacs editor, Vi editor, Less viewer, Bash shell, various web browsers, etc.
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    install -D -m 0644 $pkgfiles/gtags.tmpfiles $installdir/%libdir%/tmpfiles.d/gtags.conf
